name: GitHub Actions Demo
on: [push, ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite
      - run: sed "s/ABC1/1CBA/g" test.txt
      - run: |
          ls ${{ github.workspace }}
      - run: echo "main.yml"
      - run: echo "🍏 This job's status is ${{ job.status }}."
